version: '3.1'
services:
    db:
        container_name: posgres-db
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: 123